### ISSUE TITLE
Go 1.17

### ISSUE THREAD

**Issue by kelindar** [marniks7/bitmap-usage#1]
Just noticed that you are running benchmarks with `go 1.16.5`, have you tried running with `go 1.17` ? There was a significant improvement in how the functions are called (register based vs stack based). I assume you will get a significant performance boost across the board, may be worth trying.

**Comment by marniks7** [comment]
Hey, 
I have switched to go 1.17 some time ago, and comparison experiment is finally ready.
There is a benefit `5%` or `9%` or `none` depending on the case
https://github.com/marniks7/bitmap-usage/blob/master/docs/experiments/go1.17-vs-go1.16.md
